package is.common;

public enum UpdateArguments {
	RESOLV_FAILED, CONN_INIT, CONN_FAILED, CONN_SUCCESS, REGISTER_FAILED, LOGIN_FAILED, CHAT_UPDATE, NEW_ROUND_DRAWER, DRAW_LINE, NEW_ROUND_FINDER, DRAW_CURVE, GUESS_UPDATE, SCORE_UPDATE, END_ROUND, NEW_PLAYER, PLAYERS_UPDATE, ROUND_BEGIN;
}
