package is.controller.net;

public enum EResponse {
	CONNECTED, EXITED, LINE, NEW_ROUND, GUESSED, WORD_FOUND, WORD_FOUND_TIMEOUT, END_ROUND, SCORE_ROUND, ACCESSDENIED, COURBE, LISTEN, STOP_ROUND, CHEAT_ROUND, WELCOME;
}
